### ISSUE TITLE
Apache Directory Studio dark theme

### ISSUE THREAD

**Issue by cohoe** [cohoe/workstation#63]
https://issues.apache.org/jira/browse/DIRSTUDIO-1206

**Comment by rosimpson** [comment]
Still getting black on dark background with no way to edit the text color on ldap browser

**Comment by cohoe** [comment]
This has been fixed upstream. Haven't tried it out yet.

**Comment by cohoe** [comment]
Confirmed that after update to at least 2.0.0.v20210717-M17 and setting the theme in the window preferences it worked. and looked decent. May need to consider setting the theme in the config files here some day.
